name: Build & Tests
on:
  push

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          architecture: "x64"

      - name: Set up Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3
          poetry --version
