version: "3.7"
services:
  wewu-less-unit-tests:
    image: ${IMAGE_NAME}
    env_file:
      - .env.ci
    entrypoint:
      - poetry
      - run
      - pytest
      - "-vvv"
      - "-s"
      - tests/unit

  wewu-less-integration-tests:
    image: ${IMAGE_NAME}
    depends_on:
      - mongo
    env_file:
      - .env.ci
    entrypoint:
      - poetry
      - run
      - pytest
      - "-vvv"
      - "-s"
      - tests/integration

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: wewu
      MONGO_INITDB_ROOT_PASSWORD: wewu
