version: "3.7"
services:
  wewu-less-unit-tests:
    image: ${IMAGE_NAME}
    env_file:
      - .env.ci
    entrypoint:
      - poetry
      - run
      - pytest
      - "-vvv"
      - "-s"
      - tests/unit
