name: Build & Tests
on:
  push:
    branches: [ '**' ]

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.image-tag.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set Docker image tag
        id: image-tag
        env:
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          COMMIT_SHA: ${{ github.sha }}
        run: echo "IMAGE_TAG=${DOCKERHUB_USERNAME}/${REPOSITORY_NAME}:${COMMIT_SHA}" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.image-tag.outputs.IMAGE_TAG }}

  run_unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: [build_and_push]
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run unit tests
        env:
          IMAGE_NAME: ${{ needs.build_and_push.outputs.image_tag }}
        run: docker compose up wewu-less-unit-tests --exit-code-from=wewu-less-unit-tests


  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          architecture: "x64"

      - name: Set up Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3
          poetry --version
